[project]
name = "encies-analytics-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clickhouse-driver>=0.2.10",
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "streamlit>=1.52.0",
]
